name: Lint and Test Charts

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: "3.16.2"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        env:
          FOLDERS: incubator
          BRANCH: main
        run: |
          changed=$(ct list-changed --chart-dirs $FOLDERS --target-branch $BRANCH)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        env:
          FOLDERS: incubator
          BRANCH: main
        run: ls && ct version && ct lint --chart-dirs ${FOLDERS} --target-branch $BRANCH
#      - name: Create kind cluster
#        uses: helm/kind-action@v1.2.0
#        if: steps.list-changed.outputs.changed == 'true'
#      - name: Run chart-testing (install)
#        run: ct install
